version: '3'
services:
  data2vec:
    image: grip-dockers/data2vec:latest
    volumes:
      - ./data2wav_in:/input
      - ./data2wav_out:/output
    environment:
      - AUDIO_INPUT=/input
      - AUDIO_OUTPUT=/output
    pull_policy: never
    command: [ "python", "data2vec.py"]
    # command : tail -f /dev/null

  wav2vec:
    image: grip-dockers/wav2vec:latest
    volumes:
      - ./wav2vec_in:/input
      - ./wav2vec_out:/output
    environment:
      - AUDIO_INPUT=/input
      - AUDIO_OUTPUT=/output
    pull_policy: never

    command: [ "python", "wav2vec.py"]

